wrap_comments = true
condense_wildcard_suffixes = true
edition = "2024"
format_code_in_doc_comments = true
format_macro_matchers = true
hex_literal_case = "Upper"
inline_attribute_width = 60
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
style_edition = "2024"
max_width = 160
unstable_features = true
use_field_init_shorthand = true
